<script setup>
useSeoMeta({
    title: "Photography - Joshua Noakes",
    description: "I'm a self-taught developer, homelabber and photographer.",
    url: "https://www.joshuanoakes.co.uk/photos"
});
</script>

<template>
    <div class="grid md:grid-cols-3 sm:grid-cols-2 grid-cols-1 pl-4 pr-4 overflow-y-auto h-screen overflow-auto pb-32">
        <PhotoCard id="iratvszpssr5wwtqy3pr" ext="heic" name="Sierra County, CA" date="2024-05-10" camera="iPhone 14 Pro Max" location="39.637, -120.62" alt="The view over Tahoe National Forest from the window of a Boeing 777-200 ER. The peaks of a few large mountains can be seen along the bottom of the image with the setting sun leaving a band of pink, yellow and blue across the middle of the sky." desc="The view over Tahoe National Forest from the window of a Boeing 777-200 ER."/>
        <PhotoCard id="mupuv1gye8et8wuaid1o" ext="heic" name="Windy Beach, Rhodes" date="2022-07-13" camera="iPhone 13 Pro Max" location="36.453, 28.218" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
        <PhotoCard id="ii6xklrlskou5h8p8jps" ext="jpg" name="The London Eye" date="2023-02-15" camera="iPhone 14 Pro Max" location="51.503, -0.1197" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
        <PhotoCard id="iratvszpssr5wwtqy3pr" ext="heic" name="Sierra County, CA" date="2024-05-10" camera="iPhone 14 Pro Max" location="39.637, -120.62" alt="The view over Tahoe National Forest from the window of a Boeing 777-200 ER. The peaks of a few large mountains can be seen along the bottom of the image with the setting sun leaving a band of pink, yellow and blue across the middle of the sky." desc="The view over Tahoe National Forest from the window of a Boeing 777-200 ER."/>
        <PhotoCard id="mupuv1gye8et8wuaid1o" ext="heic" name="Windy Beach, Rhodes" date="2022-07-13" camera="iPhone 13 Pro Max" location="36.453, 28.218" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
        <PhotoCard id="ii6xklrlskou5h8p8jps" ext="jpg" name="The London Eye" date="2023-02-15" camera="iPhone 14 Pro Max" location="51.503, -0.1197" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
        <PhotoCard id="iratvszpssr5wwtqy3pr" ext="heic" name="Sierra County, CA" date="2024-05-10" camera="iPhone 14 Pro Max" location="39.637, -120.62" alt="The view over Tahoe National Forest from the window of a Boeing 777-200 ER. The peaks of a few large mountains can be seen along the bottom of the image with the setting sun leaving a band of pink, yellow and blue across the middle of the sky." desc="The view over Tahoe National Forest from the window of a Boeing 777-200 ER."/>
        <PhotoCard id="mupuv1gye8et8wuaid1o" ext="heic" name="Windy Beach, Rhodes" date="2022-07-13" camera="iPhone 13 Pro Max" location="36.453, 28.218" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
        <PhotoCard id="ii6xklrlskou5h8p8jps" ext="jpg" name="The London Eye" date="2023-02-15" camera="iPhone 14 Pro Max" location="51.503, -0.1197" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
        <PhotoCard id="iratvszpssr5wwtqy3pr" ext="heic" name="Sierra County, CA" date="2024-05-10" camera="iPhone 14 Pro Max" location="39.637, -120.62" alt="The view over Tahoe National Forest from the window of a Boeing 777-200 ER. The peaks of a few large mountains can be seen along the bottom of the image with the setting sun leaving a band of pink, yellow and blue across the middle of the sky." desc="The view over Tahoe National Forest from the window of a Boeing 777-200 ER."/>
        <PhotoCard id="mupuv1gye8et8wuaid1o" ext="heic" name="Windy Beach, Rhodes" date="2022-07-13" camera="iPhone 13 Pro Max" location="36.453, 28.218" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
        <PhotoCard id="ii6xklrlskou5h8p8jps" ext="jpg" name="The London Eye" date="2023-02-15" camera="iPhone 14 Pro Max" location="51.503, -0.1197" alt="The view out to sea from the pier of Rhodes' Windy Beach on the north west side of the island. The image features a golden sunset with the sun off to the right of the photo and a haze shimmering off the water."/>
    </div>
</template>